### ISSUE TITLE
Does LUIGI's ui support users to render a custom BOARD through a graphic or by themselves?

### ISSUE THREAD

**Issue by yuandj** [Ludeme/LudiiTutorials#3]
that the game https://ludii.games/details.php?keyword=Lam%20Turki
we found on your database.

in china, my student as volunteer, to teacher kids to paint by themself. like this.
how to adding to the LUDIITUTORIALS. AND CAN YOU give me a suggest how to folk and adding the demo.

![image](https://user-images.githubusercontent.com/14815502/108620361-b2316580-7466-11eb-9a3e-2f7f78773387.png)

that's yours :D which one is better ?

![image](https://user-images.githubusercontent.com/14815502/108620378-caa18000-7466-11eb-80af-8f01dee841b5.png)

**Comment by DennisSoemers** [comment]
Closing this issue since I believe this has all been sufficiently discussed on the forums already (https://ludii.games/forums/showthread.php?tid=446)? If there's still an unresolved issue here, please let us know!
